### ISSUE TITLE
Possible naming confusion

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-crud-tests#2]
Based on the name of this repo, I thought it was going to test backend storage solutions.

Based on the README, I see it's actually testing CRUD/WebSockets, or surface in general.

Would there be a more natural name perhaps to reflect this? (Minor obviously.)

**Comment by michielbdejong** [comment]
Thanks! I see your point. I'll consider renaming it.

**Comment by michielbdejong** [comment]
Went for splitting it into four parts:
* webid-provider-tests
* solid-crud-tests
* [websockets-pubsub-tests](https://github.com/solid/test-suite/tree/master/testers/websockets-pubsub)
* web-access-control-tests
