### ISSUE TITLE
Results should not have to be in the same order

### ISSUE THREAD

**Issue by ylebre** [solid/solid-crud-tests#42]
The comparison on: 
https://github.com/solid/solid-crud-tests/blob/f8ed1d4b67731d53e5dcfe318e2a4d8f0538ebf5/test/surface/conneg.test.ts#L377

expects the triples in the results to be in the exact same order, where they should be allowed to be different. This should be rewritten so that the order of the triples in the results do not matter.

**Comment by ylebre** [comment]
A lot of these were already fixed in #35 but it seems we have a few more loose ends.

**Comment by michielbdejong** [comment]
Done afaik, please reopen if there are any left.
